services:
  ss-postgres:
    image: postgres:latest
    container_name: ss-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    ports:
      - "${POSTGRES_DB_PORT}:5432"
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
      - ${POSTGRES_DB_DATASETS_PATH}:/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - ss

networks:
  ss:
    driver: bridge